import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";

// Components
import Navbar from "./components/Navbar";

const robotoFlex = Roboto_Flex({
  subsets: ["latin"],
  variable: "--font-roboto-flex",
  weight: ["400", "500", "600", "700"],
  display: "swap",
  style: "normal",
  preload: true,
});

export const metadata: Metadata = {
  title: "NexFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFlex.className} antialiased vsc-initialized`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
