import type { Metadata } from "next";
import { Roboto_Flex } from "next/font/google";
import "./globals.css";

// Components
import { QueryProvider } from "./components/QueryProvider";
import { Redirection } from "./utils/Redirection";

const robotFlex = Roboto_Flex({
  weight: ['400',"600","600", '700'],
  display: "swap",
  subsets: ["latin"],
  style: "normal",
});

export const metadata: Metadata = {
  title: "NexFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotFlex.className} antialiased vsc-initialized`}
      >
        <QueryProvider>
          <Redirection/>
        {children}
        </QueryProvider>
      </body>
    </html>
  );
}
